server:
  port: 8082
security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      grant-type: authorization_code
      scope: app
      access-token-uri: http://localhost:8081/oauth/token
    resource:
      userInfoUri: http://localhost:8081/user
    authorization:
      check-token-access: http://localhost:8081/oauth/check_token
  basic:
    enabled: false